name: GitHub Actions

on:
  push: 
    paths-ignore:
      - CODE_OF_CONDUCT.md
      - LICENSE.txt
      - README.md
  pull_request:
    paths-ignore:
      - CODE_OF_CONDUCT.md
      - LICENSE.txt
      - README.md
  schedule:
    - cron: '0 3 * * *'

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Run rubocop
      run: |
        gem install rubocop rubocop-rspec
        rubocop

  rspec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ 2.5, 2.6, 2.7 ]
    steps:
    - uses: actions/checkout@master
    - name: Setup Ruby 
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Run apt-get
      run: |
        sudo apt-get update
        sudo apt-get install libcurl4-openssl-dev
    - name: Bundle install
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Run rspec
      run: bundle exec rspec
      env:
        CI: true
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
